package es.unileon.rnag.cubiga.datatypes;

import es.unileon.rnag.cubiga.chromosome.Chromosome;
import es.unileon.rnag.cubiga.gen.Gen;

/**
 * Class that encapsulate all data types.
 * @author Adrian Casimiro Alvarez
 * @author Javier de Pedro Lopez
 */
public abstract class GeneticType {

	/**
	 * Generates a chromosome of the given data type.
	 * @return The chromosome generated.
	 */
	public abstract Chromosome generateChromosome();
	/**
	 * Generates a gen of the given type.
	 * @param index Sometimes the index generated is important such in RangeVector. If it doesen't matter,
	 * use 0. You can asume that simetimes this number will be autogenerated by random
	 * @return The gen generated.
	 */
	public abstract Gen generateGen(int index);
}
